import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, FileText, Users, Shield, AlertTriangle } from "lucide-react";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto py-8 px-4">
        <div className="mb-8">
          <Button 
            variant="ghost" 
            onClick={() => navigate("/")}
            className="mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Button>
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-blue-500" />
                Agreement to Terms
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                By accessing and using Masterplan ("the Service"), you agree to be bound 
                by these Terms of Service ("Terms"). If you disagree with any part of 
                these terms, you may not access the Service.
              </p>
              <p>
                These Terms constitute a legally binding agreement between you and 
                Masterplan regarding your use of our AI-powered educational content 
                creation platform.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="h-5 w-5 text-green-500" />
                Acceptable Use
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h4 className="font-semibold mb-2">You May:</h4>
                <ul className="list-disc pl-6 space-y-1 text-sm">
                  <li>Create educational content for legitimate teaching purposes</li>
                  <li>Use AI-generated content as a starting point for your courses</li>
                  <li>Export content to compatible platforms and formats</li>
                  <li>Share course materials with your students</li>
                  <li>Collaborate with other educators using our platform</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-2">You May Not:</h4>
                <ul className="list-disc pl-6 space-y-1 text-sm">
                  <li>Use the Service for illegal or harmful purposes</li>
                  <li>Generate content that violates intellectual property rights</li>
                  <li>Attempt to reverse engineer or access our AI models</li>
                  <li>Share account credentials or access with unauthorized users</li>
                  <li>Upload malicious content or attempt to harm our systems</li>
                  <li>Use the Service to create misleading or false educational content</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Content Ownership & Licensing</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h4 className="font-semibold mb-2">Your Content</h4>
                  <p className="text-sm">
                    You retain ownership of all content you create or upload to our platform. 
                    By using our Service, you grant us a limited license to process, store, 
                    and display your content solely for the purpose of providing our services.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold mb-2">AI-Generated Content</h4>
                  <p className="text-sm">
                    Content generated by our AI tools becomes your property upon creation. 
                    However, you are responsible for ensuring such content doesn't infringe 
                    on third-party rights and complies with applicable laws and regulations.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold mb-2">Platform Content</h4>
                  <p className="text-sm">
                    Our platform interface, AI models, and proprietary technology remain 
                    our exclusive property and are protected by intellectual property laws.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Shield className="h-5 w-5 text-purple-500" />
                Service Availability & Support
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                We strive to maintain high service availability but cannot guarantee 
                uninterrupted access. During the MVP phase, our service is provided 
                free of charge with best-effort support.
              </p>
              <ul className="list-disc pl-6 space-y-1 text-sm">
                <li>Service may be temporarily unavailable for maintenance</li>
                <li>We reserve the right to modify features and functionality</li>
                <li>Support is provided via email during business hours</li>
                <li>We may implement usage limits to ensure fair access</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-orange-500" />
                Disclaimers & Limitations
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h4 className="font-semibold mb-2">AI Content Disclaimer</h4>
                  <p className="text-sm">
                    AI-generated content is provided as-is and should be reviewed before 
                    use. We do not guarantee the accuracy, completeness, or appropriateness 
                    of AI-generated educational materials.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold mb-2">Service "As Is"</h4>
                  <p className="text-sm">
                    Our Service is provided "as is" without warranties of any kind. 
                    We disclaim all warranties, express or implied, including merchantability 
                    and fitness for a particular purpose.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold mb-2">Limitation of Liability</h4>
                  <p className="text-sm">
                    In no event shall Masterplan be liable for any indirect, incidental, 
                    special, or consequential damages arising from your use of the Service.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Account Termination</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                You may terminate your account at any time through your account settings. 
                We may suspend or terminate accounts that violate these Terms or for 
                other legitimate business reasons.
              </p>
              <p className="text-sm">
                Upon termination, you will lose access to the Service but may export 
                your content before account closure.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Changes to Terms</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                We reserve the right to modify these Terms at any time. We will notify 
                users of significant changes via email or platform notifications. 
                Continued use of the Service after changes constitutes acceptance.
              </p>
              <p className="text-sm">
                For questions about these Terms, contact us at legal@masterplan.ai
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default Terms;