// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrnzrinczzqufavglppn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpybnpyaW5jenpxdWZhdmdscHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTc2MjAsImV4cCI6MjA2Nzk3MzYyMH0.7bzjREvbMfdp9Oq2_5AoseWcsO_7rfZqQvJEmAwBSm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});